// For your readability, replace all '' in this file with white space
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/main.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cmain.c-o.\CortexM0\ARM_GCC_541\Debug\main.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/cyfitter_cfg.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\cyfitter_cfg.c-o.\CortexM0\ARM_GCC_541\Debug\cyfitter_cfg.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE.c-o.\CortexM0\ARM_GCC_541\Debug\BLE.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE_gatt.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE_gatt.c-o.\CortexM0\ARM_GCC_541\Debug\BLE_gatt.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE_ias.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE_ias.c-o.\CortexM0\ARM_GCC_541\Debug\BLE_ias.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE_eventHandler.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE_eventHandler.c-o.\CortexM0\ARM_GCC_541\Debug\BLE_eventHandler.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE_HAL_INT.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE_HAL_INT.c-o.\CortexM0\ARM_GCC_541\Debug\BLE_HAL_INT.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE_HAL_PVT.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE_HAL_PVT.c-o.\CortexM0\ARM_GCC_541\Debug\BLE_HAL_PVT.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE_bas.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE_bas.c-o.\CortexM0\ARM_GCC_541\Debug\BLE_bas.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/redLed.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\redLed.c-o.\CortexM0\ARM_GCC_541\Debug\redLed.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/redLed_PM.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\redLed_PM.c-o.\CortexM0\ARM_GCC_541\Debug\redLed_PM.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/Clock.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\Clock.c-o.\CortexM0\ARM_GCC_541\Debug\Clock.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/PWM.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\PWM.c-o.\CortexM0\ARM_GCC_541\Debug\PWM.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/PWM_PM.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\PWM_PM.c-o.\CortexM0\ARM_GCC_541\Debug\PWM_PM.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/BLE_bless_isr.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\BLE_bless_isr.c-o.\CortexM0\ARM_GCC_541\Debug\BLE_bless_isr.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/Cm0Start.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\Cm0Start.c-o.\CortexM0\ARM_GCC_541\Debug\Cm0Start.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/CyFlash.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\CyFlash.c-o.\CortexM0\ARM_GCC_541\Debug\CyFlash.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/CyLib.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\CyLib.c-o.\CortexM0\ARM_GCC_541\Debug\CyLib.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/cyPm.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\cyPm.c-o.\CortexM0\ARM_GCC_541\Debug\cyPm.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/cyutils.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\cyutils.c-o.\CortexM0\ARM_GCC_541\Debug\cyutils.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/CyLFClk.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\CyLFClk.c-o.\CortexM0\ARM_GCC_541\Debug\CyLFClk.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/cy_em_eeprom.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\cy_em_eeprom.c-o.\CortexM0\ARM_GCC_541\Debug\cy_em_eeprom.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/Clock_1.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\Clock_1.c-o.\CortexM0\ARM_GCC_541\Debug\Clock_1.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/Timer_ISR.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\Timer_ISR.c-o.\CortexM0\ARM_GCC_541\Debug\Timer_ISR.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/Timer.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\Timer.c-o.\CortexM0\ARM_GCC_541\Debug\Timer.o
arm-none-eabi-gcc.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-Wa,-alh=.\CortexM0\ARM_GCC_541\Debug/Timer_PM.lst-g-DDEBUG-Wall-ffunction-sections-ffat-lto-objects-O0-cGenerated_Source\PSoC4\Timer_PM.c-o.\CortexM0\ARM_GCC_541\Debug\Timer_PM.o
arm-none-eabi-as.exe-mcpu=cortex-m0-mthumb-I.-IGenerated_Source\PSoC4-alh=.\CortexM0\ARM_GCC_541\Debug/CyBootAsmGnu.lst-g-W-o.\CortexM0\ARM_GCC_541\Debug\CyBootAsmGnu.oGenerated_Source\PSoC4\CyBootAsmGnu.s
@mkdepend@C:\Users\dprdc\OneDrive\Documents\Capstone\STEMBoT-2-UEXT-Modules\Software\EZ BLE\PSoC Workspace\findMeTutorial.cydsn\CortexM0\ARM_GCC_541\Debug\SOURCE_C__ARM_GCC_GENERIC.txt
@mkdepend@C:\Users\dprdc\OneDrive\Documents\Capstone\STEMBoT-2-UEXT-Modules\Software\EZ BLE\PSoC Workspace\findMeTutorial.cydsn\CortexM0\ARM_GCC_541\Debug\SOURCE_ASM__ARM_GCC_GENERIC.txt
